import { Geist, Geist_Mono, Fraunces, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  weight: ["400", "500", "600"],
});
// Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${fraunces.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body 
      suppressHydrationWarning={true}
      className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
